export const skills = [
  { img: "https://simpleicons.org/icons/cplusplus.svg", name: "C++" },
  { img: "https://www.svgrepo.com/show/75601/java-logo.svg", name: "Java" },
  { img: "https://simpleicons.org/icons/python.svg", name: "Python" },
  { img: "https://simpleicons.org/icons/javascript.svg", name: "JavaScript" },
  { img: "https://simpleicons.org/icons/html5.svg", name: "HTML5" },
  { img: "https://simpleicons.org/icons/css.svg", name: "CSS" },
  { img: "https://www.svgrepo.com/show/333609/tailwind-css.svg", name: "Tailwind CSS" },
  { img: "https://img.icons8.com/?size=50&id=10232&format=png", name: "PHP" },
  { img: "https://img.icons8.com/?size=80&id=fncdgSAvOcfI&format=png", name: "Rest API" },
  { img: "https://img.icons8.com/?size=80&id=GSLBWFtCwo1I&format=png", name: "Redux" },
  { img: "https://simpleicons.org/icons/react.svg", name: "React.js" },
  { img: "https://www.svgrepo.com/show/369459/nodejs.svg", name: "Node.js" },
  { img: "https://simpleicons.org/icons/express.svg", name: "Express.js" },
  { img: "https://simpleicons.org/icons/mongodb.svg", name: "MongoDB" },
  { img: "https://simpleicons.org/icons/android.svg", name: "Android Development" },
  { img: "https://simpleicons.org/icons/googlecloud.svg", name: "GCP" },
  { img: "https://simpleicons.org/icons/tensorflow.svg", name: "TensorFlow" },
  { img: "https://simpleicons.org/icons/scikitlearn.svg", name: "Scikit-learn" },
  { img: "https://simpleicons.org/icons/numpy.svg", name: "NumPy" },
  { img: "https://simpleicons.org/icons/pandas.svg", name: "Pandas" },
  { img: "https://simpleicons.org/icons/git.svg", name: "Git" },
  { img: "https://simpleicons.org/icons/github.svg", name: "GitHub" },
  { img: "https://simpleicons.org/icons/postman.svg", name: "Postman" },
  { img: "https://simpleicons.org/icons/streamlit.svg", name: "Streamlit" },
  { img: "https://img.icons8.com/?size=80&id=lsOOuJ2YM6oO&format=png", name: "VS Code" },
  { img: "https://simpleicons.org/icons/jupyter.svg", name: "Jupyter Notebook" },
  { img: "https://simpleicons.org/icons/sqlite.svg", name: "SQLite" },
  { img: "https://simpleicons.org/icons/json.svg", name: "JSON" },
  { img: "https://simpleicons.org/icons/vercel.svg", name: "Vercel" },
  { img: "https://simpleicons.org/icons/googlecolab.svg", name: "Google Colab" },
];

export const projects = [
  {
    name: "Portfolio-Website",
    img: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDN8fGNvZGluZ3xlbnwwfHx8fDE2NTg0MjU5NjM&ixlib=rb-1.2.1&q=80&w=400",
    desc: "Developed a personal portfolio website to showcase projects and skills, utilizing HTML, CSS, and JavaScript for a responsive and interactive user experience.",
    tag: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "CareerBridge FullStack Web App",
    img: "/assets/project3.png",
    desc: "Built a responsive mentorship platform for Delhi NCR students, enabling 1,000+ doubt-resolution sessions and reducing admission-related queries by 80–90%, with secure authentication and MongoDB-backed data management.",
    tag: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
  },
  {
    name: "Placement Package Prediction System",
    img: "/assets/project1.png",
    desc: "Developed a machine learning model to predict placement packages for students based on their resumes on Streamlit.",
    tag: ["Python", "Pandas", "scikit-learn", "Streamlit"],
  },
  {
    name: "Resume Categorization Prediction System",
    img: "/assets/resume.jpg",
    desc: "Created a resume categorization system using NLP techniques to classify resumes into different job roles, improving recruitment efficiency by 40%.",
    tag: ["Python", "NLP", "scikit-learn"],
  },
  {
    name: "Twitter Sentiment Analysis",
    img: "/assets/twitter.jpg",
    desc: "Developed a sentiment analysis tool for Twitter data using NLP techniques, achieving 85% accuracy in classifying tweets as positive, negative, or neutral.",
    tag: ["Python", "NLP", "scikit-learn"],
  },
  {
    name: "Safe Travelling Android App",
    img: "/assets/safeTravel.jpeg",
    desc: "Developed a mobile application to ensure safe travel for users, incorporating real-time location tracking and emergency response features.",
    tag: ["Java", "Android", "Firebase"],
  },
];

export const work=[
  {
    "class":"exfirst",
    "start":"August 2024",
    "end":"October 2024",
    "name":"Data Science",
    "location":"Virtual",
    "company":"Unified Mentor",
    "tech":["ML", "Pandas", "scikit-learn"],
    "desc":"Built and deployed supervised and ensemble ML models using scikit-learn and pandas, achieving 95%+ accuracy on multiple datasets, Improved decision-making efficiency by 30% in mock business environments. Completed 5+ classification and prediction projects with a strong focus on precision, scalability, and practical impact",
    "link":"https://media.licdn.com/dms/image/v2/D562DAQH1kzKn_pOlPw/profile-treasury-image-shrink_1280_1280/profile-treasury-image-shrink_1280_1280/0/1726647794381?e=1753423201&v=beta&t=JN1pBuBaJjK6MMo0EU5_eef26kqBdSsZuoZudd8tFf8",
  },
  {
    "class":"exsecond",
    "start":"July 2024",
    "end":"September 2024",
    "name":"Google Cloude GenAI",
    "location":"Virtual",
    "company":"AICTE EduSkill",
    "tech":["Prompt Engineering", "Vertex AI", "GCP", "Kubernates", "Docker", "ML", "AI", "SQL"],
    "desc":"Engineered and deployed 20+ GenAI applications using Prompt Engineering, Google Vertex AI, and Transformer models to solve diverse real-world problems, including content generation, summarization, and intelligent search. Built and integrated a Gemini-powered chatbot for real-time PDF extraction and contextual question-answering, enhancing user engagement and reducing manual document analysis time by over 60%.",
    "link":"https://drive.google.com/file/d/1p0LFh7FanPf5j2HLlNH12d_VwhKJaEDX/view?usp=sharing",
  },
]